---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-alpine
inputs:
- name: source-code
outputs:
- name: artifact
run:
  path: sh
  args:
  - -exc
  - |
    cd source-code \
    && ./mvnw package \
    && mv target/storage-demo*.jar ../artifact/storage-demo.jar
