---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/cf-resource
    tag: latest
inputs:
- name: artifact
- name: source-code
run:
  path: sh
  args:
  - -exc
  - |
    cf api $api --skip-ssl-validation \
    && cf login -u $username -p $password \
    && cf target -o $organization -s $space
