---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/cf-resource
    tag: latest
inputs:
- name: artifact
- name: source-code
run:
  path: sh
  args:
  - -exc
  - |
    cf api $api --skip-ssl-validation \
    && cf login -u $username -p $password -o $organization -s $space \
    && cf rename $current_app_name $current_app_name-existing \
    && cf push $current_app_name -p $path -f $manifest --no-start \
    && cf bind-service $current_app_name $object_store -c '{"role": "'$object_store_role'"}' \
    && cf start $current_app_name \
    && cf map-route $current_app_name $domain --hostname $host \
    && cf delete -f $current_app_name-existing
