---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/cwest/storage-demo
    branch: master
- name: deploy-to-pcf
  type: cf
  source:
    api: {{pcf-api}}
    skip_cert_check: true
    username: {{pcf-username}}
    password: {{pcf-password}}
    organization: {{pcf-organization}}
    space: {{pcf-space}}

jobs:
- name: storage-demo
  max_in_flight: 1
  plan:
  - get: source-code
    trigger: true
  - task: build
    file: source-code/ci/tasks/build.yml
  - put: deploy-to-pcf
    params:
      path: artifact/storage-demo.jar
      current_app_name: casey-storage-sample
      manifest: source-code/manifest.yml
