---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/cwest/storage-demo
    branch: master

jobs:
- name: storage-demo
  max_in_flight: 1
  plan:
  - get: source-code
    trigger: true
  - task: build
    file: source-code/ci/tasks/build.yml
  - task: deploy-to-pcf
    file: source-code/ci/tasks/deploy.yml
    params:
      path: artifact/storage-demo.jar
      current_app_name: casey-storage-sample
      manifest: source-code/manifest.yml
      object_store: storage-service
      object_store_role: storage.objectAdmin
      api: {{pcf-api}}
      skip_cert_check: true
      username: {{pcf-username}}
      password: {{pcf-password}}
      organization: {{pcf-organization}}
      space: {{pcf-space}}
